spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 936038888003-tbj7l67t74a7v128eehjmj7l584u8fp2.apps.googleusercontent.com
            client-secret: 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
            scope: profile,email
          naver:
            client-id: m82HxrEhfqydbSEb7frc
            client-secret: dFbBQKCjs0
            redirect-uri: "{baseUrl}/{action}/oauth2/code/{registrationId}"
            authorization-grant-type: authorization_code
            scope: name, email, profile_image
          kakao:
            client-id: 3b8919edb93475c15ac6d20410446c23
            client-secret: THxSW3dmJjGBF3n89Zi5NPwaLtc84Ffo
            redirect-uri: "{baseUrl}/{action}/oauth2/code/{registrationId}"
            authorization-grant-type: authorization_code
            client-authentication-method: POST
            scope: profile_nickname, account_email, profile_image
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id